/* Reseñas consentidas: envíos privados y publicación moderada separada. */
(function(){
  'use strict';
  const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const db=()=>firebase.firestore(),auth=()=>firebase.auth(),stamp=()=>firebase.firestore.FieldValue.serverTimestamp();
  const admin=u=>u?.emailVerified&&u.email==='estudiosmira@gmail.com';
  const alias=name=>{const parts=String(name||'Clienta').trim().split(/\s+/);return (parts[0]+(parts.length>1?' '+parts.at(-1)[0].toUpperCase()+'.':'')).replace(/@.*/,'').slice(0,60)||'Clienta';};
  const photoOK=s=>!s||(typeof s==='string'&&s.length<=220000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/=]+$/.test(s));
  function validate(r){if(!Number.isInteger(r.rating)||r.rating<1||r.rating>5)throw Error('Elegí entre 1 y 5 estrellas.');if(typeof r.text!=='string'||r.text.trim().length<10||r.text.length>1500)throw Error('Escribí entre 10 y 1500 caracteres.');if(r.consent!==true)throw Error('Necesitamos tu permiso para publicar la reseña.');if(!photoOK(r.photo))throw Error('La foto debe ser un JPEG pequeño. Volvé a seleccionarla.');}
  const badge=v=>({payment:'Compra verificada',service:'Servicio realizado',access:'Acceso al producto'}[v]||'');
  function card(r){const date=r.publishedAt?.toDate?.();return `<article class="mr-card"><div class="mr-stars" aria-label="${esc(r.rating)} de 5 estrellas">${'★'.repeat(Math.max(0,Math.min(5,r.rating||0)))}${'☆'.repeat(Math.max(0,5-(r.rating||0)))}</div><p class="mr-quote">${esc(r.text)}</p>${r.photo&&photoOK(r.photo)?`<img class="mr-photo" src="${esc(r.photo)}" alt="Foto compartida por la clienta" loading="lazy">`:''}<strong>${esc(r.name)}</strong><p class="mr-meta">${esc(r.title)}</p><span class="mr-badge">${esc(badge(r.verification))}</span>${date?`<time class="mr-meta" datetime="${date.toISOString()}">${date.toLocaleDateString('es-AR')}</time>`:''}${r.reply?`<div class="mr-reply"><strong>Respuesta de Mira Estudio</strong><p>${esc(r.reply)}</p></div>`:''}</article>`;}
  function message(host,text,error=false){host.innerHTML=`<p role="${error?'alert':'status'}">${esc(text)}</p>`;}
  function session(){const u=auth().currentUser;if(!u?.emailVerified)throw Error('Ingresá con tu email verificado para dejar una reseña.');return u;}
  function same(uid){if(auth().currentUser?.uid!==uid)throw Error('La sesión cambió. Volvé a ingresar.');}
  const key=(kind,id)=>kind+'_'+id;
  async function options(u){
    const [manual,paid,services,cs,eb]=await Promise.all([
      db().collection('manualAccess/'+u.uid+'/products').get(),db().collection('entitlements').where('uid','==',u.uid).get(),db().collection('reviewServices/'+u.uid+'/items').get(),db().collection('site').doc('courses').get(),db().collection('site').doc('ebooks').get()
    ]);same(u.uid);const out=new Map(),catalog={course:cs.data()?.v||[],ebook:eb.data()?.v||[]};
    function add(d,proofId,paid){if(d.active!==true||!catalog[d.kind])return;const p=catalog[d.kind].find(p=>String(p.id)===String(d.productId));if(!p||p.locked)return;const k=key(d.kind,String(p.id));out.set(k,{targetKey:k,kind:d.kind,productId:String(p.id),title:p.title,verification:paid?'payment':'access',proofId:proofId||''});}
    manual.docs.forEach(x=>add(x.data(),'',false));paid.docs.forEach(x=>{const d=x.data();if(d.source==='admin'||(d.paymentId&&d.live===true))add(d,x.id,!!d.paymentId&&d.source!=='admin'&&d.live===true);});
    services.docs.forEach(x=>{const d=x.data();out.set(x.id,{targetKey:x.id,kind:'service',productId:d.productId,title:d.title,verification:'service',proofId:''});});return [...out.values()];
  }
  async function saveReview(target,values){
    validate(values);const u=session(),id=u.uid+'_'+target.targetKey,ref=db().collection('reviews').doc(id),pub=db().collection('publicReviews').doc(id);
    await db().runTransaction(async tx=>{const old=await tx.get(ref);same(u.uid);const payload={...target,uid:u.uid,name:alias(u.displayName||u.email?.split('@')[0]||'Clienta'),rating:values.rating,text:values.text.trim(),photo:values.photo||'',consent:true,status:'pending',reply:'',featured:false,reason:'',createdAt:old.exists?old.data().createdAt:stamp(),updatedAt:stamp()};tx.set(ref,payload);tx.delete(pub);});same(u.uid);
  }
  async function compress(file){
    if(!file||!/^image\/(jpeg|png|webp)$/.test(file.type)||file.size>8*1024*1024)throw Error('Elegí una foto JPG, PNG o WebP de hasta 8 MB.');
    const url=await new Promise((ok,no)=>{const reader=new FileReader();reader.onload=()=>ok(reader.result);reader.onerror=()=>no(Error('No pudimos leer esa foto.'));reader.readAsDataURL(file);});{const img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(Error('No pudimos abrir esa foto.'));img.src=url;});const canvas=document.createElement('canvas'),scale=Math.min(1,800/Math.max(img.width,img.height));canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);for(const quality of [.75,.55,.35,.2]){const data=canvas.toDataURL('image/jpeg',quality);if(photoOK(data))return data;}throw Error('La foto pesa demasiado. Elegí una imagen más sencilla.');}
  }
  let privateRevision=0;
  async function myReviews(){
    const host=$('#mr-mine');if(!host)return;const rev=++privateRevision;message(host,'Cargando tus experiencias…');
    try{const u=session();const [targets,saved]=await Promise.all([options(u),db().collection('reviews').where('uid','==',u.uid).get()]);same(u.uid);if(rev!==privateRevision)return;const records=new Map(saved.docs.map(x=>[x.data().targetKey,x.data()]));
      host.innerHTML='<h2>Contanos tu experiencia</h2><p>Tu opinión ayuda a otras clientas a elegir. También podés compartir qué mejorarías.</p><div class="mr-my-list"></div><div class="mr-editor"></div>';
      const list=host.querySelector('.mr-my-list');if(!targets.length)message(list,'Acá vas a poder opinar sobre tus productos habilitados y los servicios que el estudio registre como realizados.');
      for(const t of targets){const r=records.get(t.targetKey),row=document.createElement('div');row.className='mr-own-row';row.innerHTML=`<div><strong>${esc(t.title)}</strong><p>${esc(r?({pending:'Pendiente de revisión',published:'Publicada',hidden:'No publicada'}[r.status]||'Pendiente'):'Todavía no dejaste tu opinión')}${r?.reason?' · '+esc(r.reason):''}</p></div><button class="btn-g">${r?'Editar reseña':'Contanos tu experiencia'}</button>`;row.querySelector('button').onclick=()=>editor(host.querySelector('.mr-editor'),t,r);list.append(row);}
    }catch(e){if(rev!==privateRevision)return;message(host,e.message,true);const retry=document.createElement('button');retry.className='btn-g';retry.textContent='Volver a cargar';retry.onclick=myReviews;host.append(retry);}
  }
  function editor(host,target,old){
    let photo=old?.photo||'',processing=false;const u=session();host.innerHTML=`<form class="mr-form"><h3>${esc(target.title)}</h3><fieldset class="mr-rating"><legend>¿Cómo fue tu experiencia?</legend>${[1,2,3,4,5].map(n=>`<label><input type="radio" name="rating" value="${n}" ${old?.rating===n?'checked':''} required><span>${n} ★</span></label>`).join('')}</fieldset><label>Tu opinión<textarea name="opinion" required minlength="10" maxlength="1500" rows="4" placeholder="Contanos qué te gustó y qué podríamos mejorar">${esc(old?.text||'')}</textarea></label><label>Foto opcional<input name="photo" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="mr-meta">Solo fotos propias que tengas permiso para compartir. No incluyas datos personales.</p><div class="mr-preview"></div><button type="button" class="btn-g" data-remove>Quitar foto</button><label class="mr-consent"><input type="checkbox" name="consent" required> Autorizo publicar esta opinión y su foto con el nombre <strong>${esc(alias(u.displayName||u.email?.split('@')[0]))}</strong>. Mi email no se publicará.</label><p class="mr-meta">Si editás una reseña publicada, se retirará hasta que revisemos la nueva versión.</p><div role="status" class="mr-feedback"></div><button class="btn-gold" type="submit">Enviar reseña</button> <button class="btn-g" type="button" data-cancel>Cancelar</button></form>`;
    const form=host.querySelector('form'),feedback=form.querySelector('.mr-feedback'),preview=form.querySelector('.mr-preview'),submit=form.querySelector('[type=submit]');const showPhoto=()=>{preview.innerHTML=photo?`<img class="mr-photo" alt="Foto seleccionada" src="${esc(photo)}">`:'';};showPhoto();
    form.querySelector('[data-cancel]').onclick=()=>host.replaceChildren();form.querySelector('[data-remove]').onclick=()=>{photo='';form.elements.photo.value='';showPhoto();};
    form.elements.photo.onchange=async()=>{processing=true;submit.disabled=true;try{photo=await compress(form.elements.photo.files[0]);showPhoto();feedback.textContent='Foto lista.';}catch(e){feedback.textContent=e.message;}finally{processing=false;submit.disabled=false;}};
    form.onsubmit=async e=>{e.preventDefault();if(processing)return;submit.disabled=true;try{await saveReview(target,{rating:Number(form.elements.rating.value),text:form.elements.opinion.value,photo,consent:form.elements.consent.checked});await myReviews();const note=document.createElement('p');note.setAttribute('role','status');note.textContent='Gracias. Tu reseña quedó enviada para revisión.';$('#mr-mine').prepend(note);}catch(err){feedback.textContent=err.message;submit.disabled=false;}};host.scrollIntoView?.({behavior:'smooth',block:'center'});
  }
  function projection(r){const out={};for(const k of ['targetKey','kind','productId','title','name','rating','text','photo','verification','reply','featured'])out[k]=r[k];out.publishedAt=stamp();return out;}
  async function moderate(id,status,reply,featured,reason,expected){
    if(!admin(session()))throw Error('Solo administración puede revisar reseñas.');if(status==='hidden'&&!reason.trim())throw Error('Indicá el motivo: spam, insultos o datos personales.');if(reply.length>1000||reason.length>250)throw Error('La respuesta o el motivo es demasiado largo.');
    const ref=db().collection('reviews').doc(id),pub=db().collection('publicReviews').doc(id);await db().runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists)throw Error('La reseña ya no existe.');if(expected&&['text','rating','photo','name','updatedAt'].some(k=>JSON.stringify(snap.data()[k])!==JSON.stringify(expected[k])))throw Error('La clienta editó la reseña. Actualizá la lista y revisá la nueva versión.');const next={...snap.data(),status,reply:reply.trim(),featured:status==='published'&&featured,reason:status==='hidden'?reason.trim():''};tx.update(ref,{status:next.status,reply:next.reply,featured:next.featured,reason:next.reason});if(status==='published')tx.set(pub,projection(next));else tx.delete(pub);});
  }
  async function serviceForm(host){
    const [users,services]=await Promise.all([db().collection('users').get(),db().collection('site').doc('services_page').get()]);const names=[...new Set((services.data()?.v?.cats||[]).flatMap(c=>(c.items||[]).map(s=>s.n)).filter(Boolean))].sort();
    host.innerHTML=`<details class="mr-form"><summary>Registrar servicio realizado</summary><p>Habilitá una reseña solo después de atender a la clienta. Esto no registra pagos ni cambia sus accesos a cursos.</p><label>Buscar clienta<input type="search" data-search placeholder="Nombre o email"></label><label>Clienta<select data-client></select></label><label>Servicio<select data-service>${names.map(n=>`<option value="${esc(encodeURIComponent(n))}">${esc(n)}</option>`).join('')}</select></label><label>Fecha de atención<input type="date" data-date max="${new Date().toLocaleDateString('en-CA')}" required></label><button class="btn-gold" data-register>Confirmar servicio realizado</button><p role="status" data-feedback></p></details>`;
    const select=host.querySelector('[data-client]'),rows=users.docs.map(x=>({id:x.id,...x.data()}));function filter(){const q=host.querySelector('[data-search]').value.toLowerCase();select.innerHTML=rows.filter(x=>(x.name+' '+x.email).toLowerCase().includes(q)).sort((a,b)=>(a.name||'').localeCompare(b.name||'')).map(x=>`<option value="${esc(x.id)}">${esc(x.name||'Clienta')} · ${esc(x.email||'Sin email')}</option>`).join('');}filter();host.querySelector('[data-search]').oninput=filter;
    host.querySelector('[data-register]').onclick=async e=>{const button=e.currentTarget,feedback=host.querySelector('[data-feedback]');button.disabled=true;try{const uid=select.value,service=host.querySelector('[data-service]'),id=service.value,date=host.querySelector('[data-date]').value;if(!uid||!id||!date||date>new Date().toLocaleDateString('en-CA'))throw Error('Elegí clienta, servicio y una fecha de atención válida.');await db().collection('reviewServices/'+uid+'/items').doc(key('service',id)).set({productId:id,title:service.selectedOptions[0].textContent,performedOn:date});feedback.textContent='Servicio registrado. La clienta ya puede dejar su reseña desde Mi Perfil.';}catch(err){feedback.textContent=err.message;}finally{button.disabled=false;}};
  }
  async function adminReviews(){
    const host=$('#mr-admin');if(!host)return;message(host,'Cargando reseñas…');try{if(!admin(session()))throw Error('Acceso exclusivo de administración.');host.innerHTML='<h2>Reseñas de clientas y alumnas</h2><p>Revisá spam, insultos o datos personales. Publicá también las críticas legítimas. Las estrellas y el comentario pertenecen a la clienta.</p><div class="mr-service-admin"></div><label>Mostrar <select data-filter><option value="pending">Pendientes</option><option value="published">Publicadas</option><option value="hidden">No publicadas</option></select></label> <button class="btn-g" data-refresh>Actualizar</button><div class="mr-admin-list"></div><button class="btn-g" data-more>Cargar más</button>';
      let cursor=null,revision=0;const list=host.querySelector('.mr-admin-list'),more=host.querySelector('[data-more]');async function load(reset){const rev=++revision;more.disabled=true;if(reset){cursor=null;message(list,'Cargando…');}try{let q=db().collection('reviews').where('status','==',host.querySelector('[data-filter]').value).limit(12);if(cursor)q=q.startAfter(cursor);const snap=await q.get();if(rev!==revision)return;if(reset)list.replaceChildren();cursor=snap.docs.at(-1)||cursor;more.hidden=snap.docs.length<12;for(const doc of snap.docs){const r=doc.data(),row=document.createElement('div');row.className='mr-form';row.innerHTML=card(r)+`<label>Respuesta del estudio<textarea maxlength="1000" data-reply>${esc(r.reply)}</textarea></label><label><input type="checkbox" data-featured ${r.featured?'checked':''}> Destacar en el inicio</label><label>Motivo si no se publica<input maxlength="250" data-reason value="${esc(r.reason)}" placeholder="Spam, insultos o datos personales"></label><div class="mr-actions"><button class="btn-gold" data-state="published">${r.status==='published'?'Guardar respuesta y destacado':'Publicar'}</button><button class="btn-g" data-state="hidden">No publicar</button></div><p role="status" data-result></p>`;row.querySelectorAll('[data-state]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await moderate(doc.id,b.dataset.state,row.querySelector('[data-reply]').value,row.querySelector('[data-featured]').checked,row.querySelector('[data-reason]').value,r);await load(true);}catch(e){row.querySelector('[data-result]').textContent=e.message;b.disabled=false;}});list.append(row);}if(!list.children.length)message(list,'No hay reseñas en este estado.');}catch(e){if(rev===revision)message(list,'No pudimos cargar las reseñas. '+e.message,true);}finally{if(rev===revision)more.disabled=false;}}
      host.querySelector('[data-filter]').onchange=()=>load(true);host.querySelector('[data-refresh]').onclick=()=>load(true);more.onclick=()=>load(false);await Promise.all([load(true),serviceForm(host.querySelector('.mr-service-admin')).catch(e=>message(host.querySelector('.mr-service-admin'),e.message,true))]);
    }catch(e){message(host,e.message,true);}
  }
  async function publicSection(host,kind='',targetKey='',home=false){
    if(!host)return;host.classList.add('mr-section');host.innerHTML='<div class="mr-kicker">EXPERIENCIAS REALES</div><h2>'+({course:'Lo que cuentan nuestras alumnas',ebook:'Experiencias con nuestros ebooks',service:'Experiencias en el estudio'}[kind]||'La mirada de quienes nos eligen')+'</h2><p>Opiniones de clientas y alumnas sobre sus experiencias en Mira Estudio.</p><div class="mr-filters"></div><div class="mr-grid"></div><button class="btn-g" data-more>Ver más reseñas</button><p class="mr-meta">Las reseñas se revisan antes de publicarse para evitar spam y proteger datos personales.</p><a class="btn-g" href="dashboard.html?resenas=1">Contanos tu experiencia</a>';
    const grid=host.querySelector('.mr-grid'),more=host.querySelector('[data-more]');let cursor=null,revision=0,expanded=!home;
    async function load(reset=false){const rev=++revision;more.disabled=true;if(reset){cursor=null;grid.replaceChildren();}try{let q=db().collection('publicReviews');if(targetKey)q=q.where('targetKey','==',targetKey);else if(kind)q=q.where('kind','==',kind);else if(!expanded)q=q.where('featured','==',true);else q=q.orderBy('publishedAt','desc');q=q.limit(expanded?12:3);if(cursor)q=q.startAfter(cursor);let snap=await q.get();if(!expanded&&!snap.docs.length)snap=await db().collection('publicReviews').orderBy('publishedAt','desc').limit(3).get();if(rev!==revision)return;cursor=snap.docs.at(-1)||cursor;grid.insertAdjacentHTML('beforeend',snap.docs.map(x=>card(x.data())).join(''));if(!grid.children.length)message(grid,'Todavía no hay reseñas publicadas. Si ya tuviste tu experiencia, nos encantará conocerla.');more.hidden=expanded&&snap.docs.length<12;more.textContent=expanded?'Ver más reseñas':'Ver todas las reseñas';}catch(e){if(rev===revision){message(grid,'No pudimos cargar las reseñas. Volvé a intentar en un momento.',true);more.hidden=false;more.textContent='Reintentar';cursor=null;}}finally{if(rev===revision)more.disabled=false;}}
    more.onclick=()=>{if(!expanded){expanded=true;load(true);}else load(!cursor);};
    if(!targetKey){const filters=host.querySelector('.mr-filters');try{let choices=[];if(kind==='course'||kind==='ebook'){const snap=await db().collection('site').doc(kind==='course'?'courses':'ebooks').get();choices=(snap.data()?.v||[]).map(p=>({key:key(kind,String(p.id)),title:p.title}));}else if(kind==='service'){const snap=await db().collection('site').doc('services_page').get();choices=(snap.data()?.v?.cats||[]).flatMap(c=>(c.items||[]).map(s=>({key:key('service',encodeURIComponent(s.n)),title:s.n})));}if(choices.length){filters.innerHTML=`<label>Opiniones sobre <select><option value="">Todos</option>${choices.map(c=>`<option value="${esc(c.key)}">${esc(c.title)}</option>`).join('')}</select></label>`;filters.querySelector('select').onchange=e=>{targetKey=e.target.value;load(true);};}}catch{/* Las reseñas siguen disponibles si falla el catálogo de filtros. */}}
    await load(true);
  }
  function openOpinions(kind,id){
    let dialog=document.getElementById('mr-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='mr-dialog';dialog.className='mr-dialog';dialog.innerHTML='<button class="btn-g" data-close aria-label="Cerrar opiniones">Cerrar</button><div data-content></div>';dialog.querySelector('[data-close]').onclick=()=>dialog.close();document.body.append(dialog);}publicSection(dialog.querySelector('[data-content]'),kind,key(kind,String(id)));if(!dialog.open)dialog.showModal();
  }
  window.MiraReviews={alias,validate,card,openOpinions,saveReview,moderate,projection,myReviews,adminReviews,publicSection};
  document.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{
    try{if(!window.firebase?.apps?.length)return;
      const old=window.admRenderReviewsList;if(old)window.admRenderReviewsList=adminReviews;
      const oldPage=window.showPage;if(oldPage)window.showPage=function(p){oldPage(p);if(p==='perfil')myReviews();};
      const profile=$('#page-perfil');if(profile&&!$('#mr-mine')){const box=document.createElement('section');box.id='mr-mine';box.className='mr-section';profile.append(box);const nav=$('#nav-perfil');if(nav){const btn=document.createElement('button');btn.className='sb-item';btn.textContent='Mis reseñas';btn.onclick=()=>{showPage('perfil');box.scrollIntoView({behavior:'smooth'});};nav.after(btn);}}
      auth().onAuthStateChanged(u=>{privateRevision++;if($('#mr-mine')){if(u?.emailVerified)myReviews();else $('#mr-mine').replaceChildren();}if($('#mr-admin')&&!admin(u))$('#mr-admin').replaceChildren();if(u?.emailVerified&&new URLSearchParams(location.search).has('resenas')&&profile)showPage('perfil');});
      document.addEventListener('click',e=>{const b=e.target.closest('[data-review-kind]');if(b){e.preventDefault();e.stopPropagation();openOpinions(b.dataset.reviewKind,b.dataset.reviewId);}},true);
      document.querySelectorAll('[data-mira-reviews]').forEach(host=>publicSection(host,host.dataset.miraReviews,'',host.dataset.home==='true'));
      const oldInfo=window.svcInfoOpen;if(oldInfo)window.svcInfoOpen=function(...args){oldInfo(...args);const name=$('#svci-title')?.textContent,box=$('#svci-res');if(box&&name){box.style.display='';publicSection(box,'service',key('service',encodeURIComponent(name)));}};
    }catch(e){console.warn('Reseñas no disponibles',e);}
  },0);});
})();
